[package]
name = "image_process"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.24", features = ["glow"] }
egui = "0.24"
walkdir = "2.3"
image = "0.24"
winapi = { version = "0.3", features = ["winuser", "windef"] }